name: qrcodescanner
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  qrscan: ^0.2.17
  url_launcher: ^5.4.10
  flutter_linkify: ^3.1.3
  intl: ^0.16.1
  animated_widgets: ^1.0.6
  provider: ^4.1.2
  flutter_auth_buttons:
  animated_text_kit: ^2.0.0
  firebase_core: ^0.4.4+2
  firebase_auth: ^0.15.5+2
  cloud_firestore: ^0.13.4+1
  google_sign_in: ^4.1.4
  flutter_icons: ^1.1.0
  rflutter_alert:
  slimy_card: ^1.0.4
  font_awesome_flutter: ^8.8.1
  avatar_glow: ^1.2.0
  speech_recognition: ^0.3.0+1
  geolocator: ^5.3.2+2
  geoflutterfire: ^2.1.0
  timer_count_down: ^1.0.4+1
  time_formatter: ^1.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/logo.png
    - images/Crowd.jpg
    - images/How.jpg
    - images/Why.jpg
    - images/cop.jpg


